# Generated by Django 5.1.2 on 2024-10-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_privatemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='message',
            new_name='content',
        ),
    ]
