# Generated by Django 5.1 on 2024-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_rename_message_privatemessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
    ]
