# Generated by Django 5.1 on 2024-11-15 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_alter_question_options_question_is_answered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='secret_item',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='thinker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_thinker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't know", "I don't know")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chat_app.gamesession'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=500),
        ),
    ]
